version: "3.3"

services:

  mongodb:
    container_name: mongodb
    image: mvertes/alpine-mongo:latest
    restart: always
    volumes:
      - data_db:/data/db
    ports:
      - 27019:27017
    networks:
      - octonius
      
  mailing-server:
    container_name: mailing-server
    image: mailing:server
    ports:
      - 2000:2000
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./services/mailing/server
    volumes:
      - /usr/app/node_modules
    depends_on:
      - mongodb
    links:
      - mongodb
    networks:
      - octonius
      
  auths-server:
    container_name: auths-server
    image: auths:server
    ports:
      - 3002:3000
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./services/authentication/server
    volumes:
      - /usr/app/node_modules
    depends_on:
      - mongodb
    links:
      - mongodb
    networks:
      - octonius
         
  groups-server:
    container_name: groups-server
    image: groups:server
    ports:
      - 4000:4000
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./services/groups/server
    volumes:
      - /usr/app/node_modules
    depends_on:
      - mongodb
    links:
      - mongodb
    networks:
      - octonius
      
  workspaces-server:
    container_name: workspaces-server
    image: workspaces:server
    ports:
      - 5000:5000
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./services/workspaces/server
    volumes:
      - /usr/app/node_modules
    depends_on:
      - mongodb
    links:
      - mongodb
    networks:
      - octonius
      
  users-server:
    container_name: users-server
    image: users:server
    ports:
      - 7000:7000
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./services/users/server
    volumes:
      - /usr/app/node_modules
    depends_on:
      - mongodb
    links:
      - mongodb
    networks:
      - octonius
      
  posts-server:
    container_name: posts-server
    image: posts:server
    ports:
      - 8000:8000
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./services/posts/server
    volumes:
      - /usr/app/node_modules
    depends_on:
      - mongodb
    links:
      - mongodb
    networks:
      - octonius
      
  notifications-server:
    container_name: notifications-server
    image: notifications:server
    ports:
      - 9000:9000
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./services/notifications/server
    volumes:
      - /usr/app/node_modules
    depends_on:
      - mongodb
    links:
      - mongodb
    networks:
      - octonius
      
  utilities-server:
    container_name: utilities-server
    image: utilities:server
    ports:
      - 10000:10000
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./services/utilities/server
    volumes:
      - /usr/app/node_modules
    depends_on:
      - mongodb
    links:
      - mongodb
    networks:
      - octonius
      
  client:
    container_name: client
    image: client
    build:
      dockerfile: Dockerfile
      context: ./client-upgrade/client
    volumes:
      - /usr/app/node_modules
      - ${PWD}/client-upgrade/client:/usr/app
    depends_on:
      - mailing-server
      - auths-server
      - groups-server
      - workspaces-server
      - users-server
      - posts-server
      - notifications-server
      - utilities-server
    networks:
      - octonius

  nginx:
    container_name: nginx
    image: nginx
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - 8080:80
    depends_on:
      - mailing-server
      - auths-server
      - groups-server
      - workspaces-server
      - users-server
      - posts-server
      - notifications-server
      - utilities-server
      - client
    networks:
      - octonius

volumes:
  data_db:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data/db
      o: bind

  data_uploads:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data/uploads
      o: bind
      
networks:
  octonius: {}