version: "3.3"

services:

  mongodb:
    container_name: mongodb
    image: mvertes/alpine-mongo:latest
    restart: always
    volumes:
      - data_db:/data/db
    ports:
      - 27018:27017
    networks:
      - octonius
      
  mailing-server:
    container_name: mailing-server
    image: octoniusapp/octonius-alpha:mailing-server
    ports:
      - 2000:2000
    restart: always
    volumes:
      - /usr/app/node_modules
    environment:
      - NODE_ENV=production
      - PORT=2000
      - HOST=0.0.0.0
      - JWT_KEY=asfsaf12safas23fsafa12sf
      - dbURL=mongodb://mongodb:27017/octonius
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SENDGRID_KEY=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
      - SK_STRIPE=sk_live_WupyMoQf93S59gwTqmYpmWel
      - stripe_plan=plan_EK1rDLfKr9NRkU
      - WEBHOOK_PS_SECRET=whsec_pmcLdxoYxBAdZswT2ZzWYep2WmnBW8Sn
      - HEADER_EXTERNAL_KEY=HEADERIDSHAREDFOROCTONIUS
      - PROTOCOL=https
      - DOMAIN=flash.octonius.com
    depends_on:
      - mongodb
    links:
      - mongodb
    networks:
      - octonius
      
  auths-server:
    container_name: auths-server
    image: octoniusapp/octonius-alpha:auths-server
    ports:
      - 3002:3000
    restart: always
    volumes:
      - /usr/app/node_modules
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOST=0.0.0.0
      - JWT_KEY=asfsaf12safas23fsafa12sf
      - dbURL=mongodb://mongodb:27017/octonius
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SENDGRID_KEY=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
      - SK_STRIPE=sk_live_WupyMoQf93S59gwTqmYpmWel
      - stripe_plan=plan_EK1rDLfKr9NRkU
      - WEBHOOK_PS_SECRET=whsec_pmcLdxoYxBAdZswT2ZzWYep2WmnBW8Sn
      - HEADER_EXTERNAL_KEY=HEADERIDSHAREDFOROCTONIUS
      - PROTOCOL=https
      - DOMAIN=flash.octonius.com
    depends_on:
      - mongodb
    links:
      - mongodb
    networks:
      - octonius
         
  groups-server:
    container_name: groups-server
    image: octoniusapp/octonius-alpha:groups-server
    ports:
      - 4000:4000
    restart: always
    volumes:
      - /usr/app/node_modules
    environment:
      - NODE_ENV=production
      - PORT=4000
      - HOST=0.0.0.0
      - JWT_KEY=asfsaf12safas23fsafa12sf
      - dbURL=mongodb://mongodb:27017/octonius
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SENDGRID_KEY=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
      - SK_STRIPE=sk_live_WupyMoQf93S59gwTqmYpmWel
      - stripe_plan=plan_EK1rDLfKr9NRkU
      - WEBHOOK_PS_SECRET=whsec_pmcLdxoYxBAdZswT2ZzWYep2WmnBW8Sn
      - HEADER_EXTERNAL_KEY=HEADERIDSHAREDFOROCTONIUS
      - PROTOCOL=https
      - DOMAIN=flash.octonius.com
    depends_on:
      - mongodb
    links:
      - mongodb
    networks:
      - octonius
      
  workspaces-server:
    container_name: workspaces-server
    image: octoniusapp/octonius-alpha:workspaces-server
    ports:
      - 5000:5000
    restart: always
    volumes:
      - /usr/app/node_modules
    environment:
      - NODE_ENV=production
      - PORT=5000
      - HOST=0.0.0.0
      - JWT_KEY=asfsaf12safas23fsafa12sf
      - dbURL=mongodb://mongodb:27017/octonius
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SENDGRID_KEY=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
      - SK_STRIPE=sk_live_WupyMoQf93S59gwTqmYpmWel
      - stripe_plan=plan_EK1rDLfKr9NRkU
      - WEBHOOK_PS_SECRET=whsec_pmcLdxoYxBAdZswT2ZzWYep2WmnBW8Sn
      - HEADER_EXTERNAL_KEY=HEADERIDSHAREDFOROCTONIUS
      - PROTOCOL=https
      - DOMAIN=flash.octonius.com
    depends_on:
      - mongodb
    links:
      - mongodb
    networks:
      - octonius
      
  users-server:
    container_name: users-server
    image: octoniusapp/octonius-alpha:users-server
    ports:
      - 7000:7000
    restart: always
    volumes:
      - /usr/app/node_modules
    environment:
      - NODE_ENV=production
      - PORT=7000
      - HOST=0.0.0.0
      - JWT_KEY=asfsaf12safas23fsafa12sf
      - dbURL=mongodb://mongodb:27017/octonius
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SENDGRID_KEY=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
      - SK_STRIPE=sk_live_WupyMoQf93S59gwTqmYpmWel
      - stripe_plan=plan_EK1rDLfKr9NRkU
      - WEBHOOK_PS_SECRET=whsec_pmcLdxoYxBAdZswT2ZzWYep2WmnBW8Sn
      - HEADER_EXTERNAL_KEY=HEADERIDSHAREDFOROCTONIUS
      - PROTOCOL=https
      - DOMAIN=flash.octonius.com
    depends_on:
      - mongodb
    links:
      - mongodb
    networks:
      - octonius
      
  posts-server:
    container_name: posts-server
    image: octoniusapp/octonius-alpha:posts-server
    ports:
      - 8000:8000
    restart: always
    volumes:
      - /usr/app/node_modules
    environment:
      - NODE_ENV=production
      - PORT=8000
      - HOST=0.0.0.0
      - JWT_KEY=asfsaf12safas23fsafa12sf
      - dbURL=mongodb://mongodb:27017/octonius
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SENDGRID_KEY=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
      - SK_STRIPE=sk_live_WupyMoQf93S59gwTqmYpmWel
      - stripe_plan=plan_EK1rDLfKr9NRkU
      - WEBHOOK_PS_SECRET=whsec_pmcLdxoYxBAdZswT2ZzWYep2WmnBW8Sn
      - HEADER_EXTERNAL_KEY=HEADERIDSHAREDFOROCTONIUS
      - PROTOCOL=https
      - DOMAIN=flash.octonius.com
    depends_on:
      - mongodb
    links:
      - mongodb
    networks:
      - octonius
      
  notifications-server:
    container_name: notifications-server
    image: octoniusapp/octonius-alpha:notifications-server
    ports:
      - 9000:9000
    restart: always
    volumes:
      - /usr/app/node_modules
    environment:
      - NODE_ENV=production
      - PORT=9000
      - HOST=0.0.0.0
      - JWT_KEY=asfsaf12safas23fsafa12sf
      - dbURL=mongodb://mongodb:27017/octonius
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SENDGRID_KEY=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
      - SK_STRIPE=sk_live_WupyMoQf93S59gwTqmYpmWel
      - stripe_plan=plan_EK1rDLfKr9NRkU
      - WEBHOOK_PS_SECRET=whsec_pmcLdxoYxBAdZswT2ZzWYep2WmnBW8Sn
      - HEADER_EXTERNAL_KEY=HEADERIDSHAREDFOROCTONIUS
      - PROTOCOL=https
      - DOMAIN=flash.octonius.com
    depends_on:
      - mongodb
    links:
      - mongodb
    networks:
      - octonius
      
  utilities-server:
    container_name: utilities-server
    image: octoniusapp/octonius-alpha:utilities-server
    ports:
      - 10000:10000
    restart: always
    volumes:
      - /usr/app/node_modules
    environment:
      - NODE_ENV=production
      - PORT=10000
      - HOST=0.0.0.0
      - JWT_KEY=asfsaf12safas23fsafa12sf
      - dbURL=mongodb://mongodb:27017/octonius
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SENDGRID_KEY=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
      - SK_STRIPE=sk_live_WupyMoQf93S59gwTqmYpmWel
      - stripe_plan=plan_EK1rDLfKr9NRkU
      - WEBHOOK_PS_SECRET=whsec_pmcLdxoYxBAdZswT2ZzWYep2WmnBW8Sn
      - HEADER_EXTERNAL_KEY=HEADERIDSHAREDFOROCTONIUS
      - PROTOCOL=https
      - DOMAIN=flash.octonius.com
    depends_on:
      - mongodb
    links:
      - mongodb
    networks:
      - octonius
      
  client:
    container_name: client
    image: octoniusapp/octonius-alpha:client
    volumes:
      - /usr/app/node_modules
      - ${PWD}/client-upgrade/client:/usr/app
    depends_on:
      - mailing-server
      - auths-server
      - groups-server
      - workspaces-server
      - users-server
      - posts-server
      - notifications-server
      - utilities-server
    networks:
      - octonius

  nginx:
    container_name: nginx
    image: octoniusapp/octonius-alpha:nginx
    restart: always
    ports:
      - 8080:80
    depends_on:
      - mailing-server
      - auths-server
      - groups-server
      - workspaces-server
      - users-server
      - posts-server
      - notifications-server
      - utilities-server
      - client
    networks:
      - octonius

volumes:
  data_db:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data/db
      o: bind

  data_uploads:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data/uploads
      o: bind
      
networks:
  octonius: {}