version: "3.3"

services:

  mongodb:
    container_name: mongodb
    image: mongo:latest
    restart: always
    volumes:
      - production_db_data:/data/db
    ports:
      - 27017:27017
    networks:
      - production
      
  mailing-server:
    container_name: mailing-server
    image: mailing-server
    ports:
      - 2000:2000
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./services/mailing/server
    volumes:
      - /usr/app/node_modules
    environment:
      - NODE_ENV=production
      - PORT=2000
      - HOST=0.0.0.0
      - JWT_KEY=asfsaf12safas23fsafa12sf
      - DB_URL=mongodb://mongodb:27017/octonius
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SENDGRID_KEY=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
      - SK_STRIPE=sk_live_WupyMoQf93S59gwTqmYpmWel
      - STRIPE_PLAN=plan_EK1rDLfKr9NRkU
      - WEBHOOK_PS_SECRET=whsec_pmcLdxoYxBAdZswT2ZzWYep2WmnBW8Sn
      - HEADER_EXTERNAL_KEY=HEADERIDSHAREDFOROCTONIUS
      - PROTOCOL=http
      - DOMAIN=localhost
    depends_on:
      - mongodb
    links:
      - mongodb
    networks:
      - production
      
  auths-server:
    container_name: auths-server
    image: auths-server
    ports:
      - 3000:3000
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./services/authentication/server
    volumes:
      - /usr/app/node_modules
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOST=0.0.0.0
      - JWT_KEY=asfsaf12safas23fsafa12sf
      - DB_URL=mongodb://mongodb:27017/octonius
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SENDGRID_KEY=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
      - SK_STRIPE=sk_live_WupyMoQf93S59gwTqmYpmWel
      - STRIPE_PLAN=plan_EK1rDLfKr9NRkU
      - WEBHOOK_PS_SECRET=whsec_pmcLdxoYxBAdZswT2ZzWYep2WmnBW8Sn
      - HEADER_EXTERNAL_KEY=HEADERIDSHAREDFOROCTONIUS
      - PROTOCOL=http
      - DOMAIN=localhost
    depends_on:
      - mongodb
    links:
      - mongodb
    networks:
      - production
         
  groups-server:
    container_name: groups-server
    image: groups-server
    ports:
      - 4000:4000
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./services/groups/server
    volumes:
      - /usr/app/node_modules
    environment:
      - NODE_ENV=production
      - PORT=4000
      - HOST=0.0.0.0
      - JWT_KEY=asfsaf12safas23fsafa12sf
      - DB_URL=mongodb://mongodb:27017/octonius
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SENDGRID_KEY=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
      - SK_STRIPE=sk_live_WupyMoQf93S59gwTqmYpmWel
      - STRIPE_PLAN=plan_EK1rDLfKr9NRkU
      - WEBHOOK_PS_SECRET=whsec_pmcLdxoYxBAdZswT2ZzWYep2WmnBW8Sn
      - HEADER_EXTERNAL_KEY=HEADERIDSHAREDFOROCTONIUS
      - PROTOCOL=http
      - DOMAIN=localhost
    depends_on:
      - mongodb
    links:
      - mongodb
    networks:
      - production
      
  workspaces-server:
    container_name: workspaces-server
    image: workspaces-server
    ports:
      - 5000:5000
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./services/workspaces/server
    volumes:
      - /usr/app/node_modules
    environment:
      - NODE_ENV=production
      - PORT=5000
      - HOST=0.0.0.0
      - JWT_KEY=asfsaf12safas23fsafa12sf
      - DB_URL=mongodb://mongodb:27017/octonius
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SENDGRID_KEY=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
      - SK_STRIPE=sk_live_WupyMoQf93S59gwTqmYpmWel
      - STRIPE_PLAN=plan_EK1rDLfKr9NRkU
      - WEBHOOK_PS_SECRET=whsec_pmcLdxoYxBAdZswT2ZzWYep2WmnBW8Sn
      - HEADER_EXTERNAL_KEY=HEADERIDSHAREDFOROCTONIUS
      - PROTOCOL=http
      - DOMAIN=localhost
    depends_on:
      - mongodb
    links:
      - mongodb
    networks:
      - production
      
  search-server:
    container_name: search-server
    image: search-server
    ports:
      - 12000:12000
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./services/search/server
    volumes:
      - /usr/app/node_modules
    environment:
      - NODE_ENV=production
      - PORT=12000
      - HOST=0.0.0.0
      - JWT_KEY=asfsaf12safas23fsafa12sf
      - DB_URL=mongodb://mongodb:27017/octonius
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SENDGRID_KEY=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
      - SK_STRIPE=sk_live_WupyMoQf93S59gwTqmYpmWel
      - STRIPE_PLAN=plan_EK1rDLfKr9NRkU
      - WEBHOOK_PS_SECRET=whsec_pmcLdxoYxBAdZswT2ZzWYep2WmnBW8Sn
      - HEADER_EXTERNAL_KEY=HEADERIDSHAREDFOROCTONIUS
      - PROTOCOL=http
      - DOMAIN=localhost
    depends_on:
      - mongodb
    links:
      - mongodb
    networks:
      - production
      
  users-server:
    container_name: users-server
    image: users-server
    ports:
      - 7000:7000
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./services/users/server
    volumes:
      - /usr/app/node_modules
    environment:
      - NODE_ENV=production
      - PORT=7000
      - HOST=0.0.0.0
      - JWT_KEY=asfsaf12safas23fsafa12sf
      - DB_URL=mongodb://mongodb:27017/octonius
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SENDGRID_KEY=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
      - SK_STRIPE=sk_live_WupyMoQf93S59gwTqmYpmWel
      - STRIPE_PLAN=plan_EK1rDLfKr9NRkU
      - WEBHOOK_PS_SECRET=whsec_pmcLdxoYxBAdZswT2ZzWYep2WmnBW8Sn
      - HEADER_EXTERNAL_KEY=HEADERIDSHAREDFOROCTONIUS
      - PROTOCOL=http
      - DOMAIN=localhost
    depends_on:
      - mongodb
    links:
      - mongodb
    networks:
      - production
      
  posts-server:
    container_name: posts-server
    image: posts-server
    ports:
      - 8000:8000
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./services/posts/server
    volumes:
      - /usr/app/node_modules
    environment:
      - NODE_ENV=production
      - PORT=8000
      - HOST=0.0.0.0
      - JWT_KEY=asfsaf12safas23fsafa12sf
      - DB_URL=mongodb://mongodb:27017/octonius
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SENDGRID_KEY=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
      - SK_STRIPE=sk_live_WupyMoQf93S59gwTqmYpmWel
      - STRIPE_PLAN=plan_EK1rDLfKr9NRkU
      - WEBHOOK_PS_SECRET=whsec_pmcLdxoYxBAdZswT2ZzWYep2WmnBW8Sn
      - HEADER_EXTERNAL_KEY=HEADERIDSHAREDFOROCTONIUS
      - PROTOCOL=http
      - DOMAIN=localhost
    depends_on:
      - mongodb
    links:
      - mongodb
    networks:
      - production
      
  notifications-server:
    container_name: notifications-server
    image: notifications-server
    ports:
      - 9000:9000
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./services/notifications/server
    volumes:
      - /usr/app/node_modules
    environment:
      - NODE_ENV=production
      - PORT=9000
      - HOST=0.0.0.0
      - JWT_KEY=asfsaf12safas23fsafa12sf
      - DB_URL=mongodb://mongodb:27017/octonius
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SENDGRID_KEY=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
      - SK_STRIPE=sk_live_WupyMoQf93S59gwTqmYpmWel
      - STRIPE_PLAN=plan_EK1rDLfKr9NRkU
      - WEBHOOK_PS_SECRET=whsec_pmcLdxoYxBAdZswT2ZzWYep2WmnBW8Sn
      - HEADER_EXTERNAL_KEY=HEADERIDSHAREDFOROCTONIUS
      - PROTOCOL=http
      - DOMAIN=localhost
    depends_on:
      - mongodb
    links:
      - mongodb
    networks:
      - production
      
  utilities-server:
    container_name: utilities-server
    image: utilities-server
    ports:
      - 10000:10000
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./services/utilities/server
    volumes:
      - /usr/app/node_modules
    environment:
      - NODE_ENV=production
      - PORT=10000
      - HOST=0.0.0.0
      - JWT_KEY=asfsaf12safas23fsafa12sf
      - DB_URL=mongodb://mongodb:27017/octonius
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SENDGRID_KEY=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
      - SK_STRIPE=sk_live_WupyMoQf93S59gwTqmYpmWel
      - STRIPE_PLAN=plan_EK1rDLfKr9NRkU
      - WEBHOOK_PS_SECRET=whsec_pmcLdxoYxBAdZswT2ZzWYep2WmnBW8Sn
      - HEADER_EXTERNAL_KEY=HEADERIDSHAREDFOROCTONIUS
      - PROTOCOL=http
      - DOMAIN=localhost
    depends_on:
      - mongodb
    links:
      - mongodb
    networks:
      - production

  folio-server:
    container_name: folio-server
    image: folio-server
    ports:
      - 11000:11000
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./services/folio/server
    volumes:
      - /usr/app/node_modules
    environment:
      - NODE_ENV=production
      - PORT=11000
      - HOST=0.0.0.0
      - JWT_KEY=asfsaf12safas23fsafa12sf
      - DB_URL=mongodb://mongodb:27017/octonius
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SENDGRID_KEY=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
      - SK_STRIPE=sk_live_WupyMoQf93S59gwTqmYpmWel
      - STRIPE_PLAN=plan_EK1rDLfKr9NRkU
      - WEBHOOK_PS_SECRET=whsec_pmcLdxoYxBAdZswT2ZzWYep2WmnBW8Sn
      - HEADER_EXTERNAL_KEY=HEADERIDSHAREDFOROCTONIUS
      - PROTOCOL=http
      - DOMAIN=localhost
    depends_on:
      - mongodb
    links:
      - mongodb
    networks:
      - production

  integrations-server:
    container_name: integrations-server
    image: integrations-server
    ports:
      - 13000:13000
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./services/integrations/server
    volumes:
      - /usr/app/node_modules
    environment:
      - NODE_ENV=production
      - PORT=13000
      - HOST=0.0.0.0
      - JWT_KEY=asfsaf12safas23fsafa12sf
      - DB_URL=mongodb://mongodb:27017/octonius
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SENDGRID_KEY=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
      - SK_STRIPE=sk_live_WupyMoQf93S59gwTqmYpmWel
      - STRIPE_PLAN=plan_EK1rDLfKr9NRkU
      - WEBHOOK_PS_SECRET=whsec_pmcLdxoYxBAdZswT2ZzWYep2WmnBW8Sn
      - HEADER_EXTERNAL_KEY=HEADERIDSHAREDFOROCTONIUS
      - PROTOCOL=http
      - DOMAIN=localhost
    depends_on:
      - mongodb
    links:
      - mongodb
    networks:
      - production

  client:
    container_name: client
    image: client
    build:
      dockerfile: Dockerfile
      context: ./client
    volumes:
      - /usr/app/node_modules
      - ${PWD}/client:/usr/app
    depends_on:
      - mongodb
      - mailing-server
      - auths-server
      - groups-server
      - workspaces-server
      - users-server
      - posts-server
      - notifications-server
      - utilities-server
      - folio-server
      - search-server
      - integrations-server
    networks:
      - production

  management:
    container_name: management
    image: management
    build:
      dockerfile: Dockerfile
      context: ./management
    volumes:
      - /usr/app/node_modules
      - ${PWD}/management:/usr/app
    depends_on:
      - mongodb
      - auths-server
      - groups-server
      - workspaces-server
      - users-server
      - posts-server
      - utilities-server
    networks:
      - production

  nginx:
    container_name: nginx
    image: nginx
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - 8080:80
    depends_on:
      - mongodb
      - mailing-server
      - auths-server
      - groups-server
      - workspaces-server
      - users-server
      - posts-server
      - notifications-server
      - utilities-server
      - folio-server
      - search-server
      - integrations-server
      - client
    networks:
      - production

volumes:
  production_db_data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data/db
      o: bind

  production_groups_uploads_data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data/uploads/groups
      o: bind
  
  production_posts_uploads_data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data/uploads/posts
      o: bind

  production_users_uploads_data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data/uploads/users
      o: bind

  production_workspaces_uploads_data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data/uploads/workspaces
      o: bind

  production_utilities_uploads_data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data/uploads/utilities
      o: bind
      
networks:
  production: 
    driver: bridge
