version: "3.3"

services:

  mongodb:
    container_name: groups-mongo
    image: mvertes/alpine-mongo:latest
    restart: always
    volumes:
      - data:/data/db
    ports:
      - '27017:27017'

  groups-server:
    container_name: groups-server
    image: groups:server
    restart: always
    ports:
      - '4000:4000'
    build:
      dockerfile: Dockerfile
      context: ./server
    volumes:
      - /usr/app/node_modules
    depends_on:
      - mongodb
    links:
      - mongodb

  # groups-client:
  #   container_name: groups-client
  #   image: groups:client
  #   build:
  #     dockerfile: Dockerfile
  #     context: ./client
  #   volumes:
  #     - /app/node_modules

  #     # mount client folder inside container's app folder
  #     - ${PWD}/client:/app 
  #   depends_on:
  #     - groups-server
  
  # groups-nginx:
  #   container_name: groups-nginx
  #   image: groups:nginx
  #   restart: always
  #   build:
  #     dockerfile: Dockerfile
  #     context: ./nginx
  #   ports:
  #     - 80:80
  #   depends_on:
  #     - groups-server
  #     - groups-client

volumes:
  data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data/db
      o: bind