version: "3.3"

services:

  mongodb:
    container_name: groups-mongo
    image: mongo:latest
    restart: always
    volumes:
      - data:/data/db
    ports:
      - 27017:27017

  server:
    container_name: groups-server
    image: groups:server
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./server
    volumes:
      # Avoid overwriting container's node_modules folder
      - /usr/app/node_modules
    depends_on:
      - mongodb
    links:
      - mongodb

  client:
    container_name: groups-client
    image: groups:client
    build:
      dockerfile: Dockerfile
      context: ./client
    volumes:
       # Avoid overwriting container's node_modules folder
      - /app/node_modules

      # mount client folder inside container's app folder
      - ${PWD}/client:/app 
    depends_on:
      - server
  
  nginx:
    container_name: groups-nginx
    image: groups:nginx
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - 3000:80
    depends_on:
      - server
      - client

volumes:
  data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data/db
      o: bind