apiVersion: apps/v1
kind: Deployment
metadata:
  name: solr-production-v1
  namespace: default
  labels:
    app: solr-production-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      run: solr-production-v1
  template:
    metadata:
      labels:
        run: solr-production-v1
    spec:
      containers:
        - name: solr-production-v1
          image: solr:7.7.1
          readinessProbe:
            initialDelaySeconds: 15
            periodSeconds: 5
            httpGet:
              scheme: "HTTP"
              path: /solr/admin/info/system
              port: 8983
          livenessProbe:
            initialDelaySeconds: 20
            periodSeconds: 10
            httpGet:
              scheme: "HTTP"
              path: /solr/admin/info/system
              port: 8983
          command: ["solr-precreate"]
          args: ["octonius"]
          ports:
            - containerPort: 8983
          resources:
            requests:
              memory: "32Mi"
              cpu: 100m
            limits:
              memory: "768Mi"
              cpu: 500m
          volumeMounts:
            - mountPath: /opt/solr/server/solr/octonius
              name: solr-persistent-volume-claim
      volumes:
        - name: solr-persistent-volume-claim
