kind: Service
apiVersion: v1
metadata:
  name: solr-production-v1
  namespace: default
spec:
  ports:
    - protocol: TCP
      port: 8983
      targetPort: 8983
  selector:
    run: solr-production-v1
  type: NodePort
