apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2h1Yi5kb2NrZXIuY29tLyI6eyJ1c2VybmFtZSI6Im9jdG9uaXVzYXBwIiwicGFzc3dvcmQiOiJ2ZXZlcml0YSIsImVtYWlsIjoiYW5naGVsZGFuYWRyaWFuQGdtYWlsLmNvbSIsImF1dGgiOiJiMk4wYjI1cGRYTmhjSEE2ZG1WMlpYSnBkR0U9In19fQ==
kind: Secret
metadata:
  creationTimestamp: "2020-01-19T11:22:03Z"
  name: regcred
  namespace: default
  resourceVersion: "230941"
  selfLink: /api/v1/namespaces/default/secrets/regcred
  uid: eb4aaf86-3aad-11ea-b073-42010a9c013f
type: kubernetes.io/dockerconfigjson
