apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: query-service-production
  name: query-service-production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: query-service-production
  template:
    metadata:
      labels:
        app: query-service-production
    spec:
      containers:
        - env:
            - name: JAVA_OPTS
              value: "-Xms128m -Xmx512m"
            - name: SERVER_PORT
              value: "8080"
            - name: APPLICATION_CONFIG_SOLR_CLIENT_URL
              value: "http://35.246.133.44:8983/solr"
          name: query-service-app
          image: octoniusapp/query-service:latest
          imagePullPolicy: Always
          resources:
            requests:
              memory: "512Mi"
            limits:
              memory: "512Mi"
      imagePullSecrets:
        - name: dockersecret
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: query-service-production
  name: query-service-production
spec:
  selector:
    app: query-service-production
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: http
  type: LoadBalancer
  loadBalancerSourceRanges:
    - 86.120.234.1/32
    - 111.91.228.131/32

