apiVersion: apps/v1
kind: Deployment
metadata:
  name: solrpersistent
  labels:
    app: solrpersistent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: solrpersistent
  template:
    metadata:
      labels:
        app: solrpersistent
    spec:
      containers:
        - name: solrpersistent
          image: solr:7.7.1
          command: ["solr-precreate"]
          args: ["octonius"]
          ports:
            - containerPort: 8983
          resources:
            requests:
              memory: "32Mi"
              cpu: 100m
            limits:
              memory: "768Mi"
              cpu: 500m
          volumeMounts:
            - mountPath: /opt/solr/server/solr/octonius
              name: solr-persistent-volume-claim
      volumes:
        - name: solr-persistent-volume-claim
---
kind: Service
apiVersion: v1
metadata:
  name: solrpersistent
spec:
  selector:
    app: solrpersistent
  ports:
    - protocol: TCP
      port: 8983
      targetPort: 8983
      name: http
  type: LoadBalancer
  loadBalancerSourceRanges:
    - 86.120.237.1/32
    - 111.91.228.131/32
