version: '3.7'

services:

  mongodb:
    image: mongo
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      resources:
        reservations:
          memory: 128M
        limits:
          memory: 256M
    ports:
      - 27017:27017
    networks:
      - production
    volumes:
      - production_db_data:/data/db

  mailing-server:
    image: octoniusapp/octonius-prod:mailing-server
    ports:
      - 2000:2000
    volumes:
      - /usr/app/node_modules
    environment:
      - NODE_ENV=production
      - PORT=2000
      - HOST=0.0.0.0
      - JWT_KEY=asfsaf12safas23fsafa12sf
      - dbURL=mongodb://mongodb:27017/octonius
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SENDGRID_KEY=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
      - SK_STRIPE=sk_live_WupyMoQf93S59gwTqmYpmWel
      - stripe_plan=plan_EK1rDLfKr9NRkU
      - WEBHOOK_PS_SECRET=whsec_pmcLdxoYxBAdZswT2ZzWYep2WmnBW8Sn
      - HEADER_EXTERNAL_KEY=HEADERIDSHAREDFOROCTONIUS
      - PROTOCOL=https
      - DOMAIN=app.octonius.com
    depends_on:
      - mongodb
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    networks:
      - production
      
  auths-server:
    image: octoniusapp/octonius-prod:auths-server
    ports:
      - 3000:3000
    volumes:
      - /usr/app/node_modules
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOST=0.0.0.0
      - JWT_KEY=asfsaf12safas23fsafa12sf
      - dbURL=mongodb://mongodb:27017/octonius
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SENDGRID_KEY=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
      - SK_STRIPE=sk_live_WupyMoQf93S59gwTqmYpmWel
      - stripe_plan=plan_EK1rDLfKr9NRkU
      - WEBHOOK_PS_SECRET=whsec_pmcLdxoYxBAdZswT2ZzWYep2WmnBW8Sn
      - HEADER_EXTERNAL_KEY=HEADERIDSHAREDFOROCTONIUS
      - PROTOCOL=https
      - DOMAIN=app.octonius.com
    depends_on:
      - mongodb
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    networks:
      - production
         
  groups-server:
    image: octoniusapp/octonius-prod:groups-server
    ports:
      - 4000:4000
    volumes:
      - /usr/app/node_modules
      - production_groups_uploads_data:/usr/app/uploads
    environment:
      - NODE_ENV=production
      - PORT=4000
      - HOST=0.0.0.0
      - JWT_KEY=asfsaf12safas23fsafa12sf
      - dbURL=mongodb://mongodb:27017/octonius
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SENDGRID_KEY=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
      - SK_STRIPE=sk_live_WupyMoQf93S59gwTqmYpmWel
      - stripe_plan=plan_EK1rDLfKr9NRkU
      - WEBHOOK_PS_SECRET=whsec_pmcLdxoYxBAdZswT2ZzWYep2WmnBW8Sn
      - HEADER_EXTERNAL_KEY=HEADERIDSHAREDFOROCTONIUS
      - PROTOCOL=https
      - DOMAIN=app.octonius.com
    depends_on:
      - mongodb
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    networks:
      - production
      
  workspaces-server:
    image: octoniusapp/octonius-prod:workspaces-server
    ports:
      - 5000:5000
    volumes:
      - /usr/app/node_modules
      - production_workspaces_uploads_data:/usr/app/uploads
    environment:
      - NODE_ENV=production
      - PORT=5000
      - HOST=0.0.0.0
      - JWT_KEY=asfsaf12safas23fsafa12sf
      - dbURL=mongodb://mongodb:27017/octonius
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SENDGRID_KEY=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
      - SK_STRIPE=sk_live_WupyMoQf93S59gwTqmYpmWel
      - stripe_plan=plan_EK1rDLfKr9NRkU
      - WEBHOOK_PS_SECRET=whsec_pmcLdxoYxBAdZswT2ZzWYep2WmnBW8Sn
      - HEADER_EXTERNAL_KEY=HEADERIDSHAREDFOROCTONIUS
      - PROTOCOL=https
      - DOMAIN=app.octonius.com
    depends_on:
      - mongodb
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    networks:
      - production
      
  users-server:
    image: octoniusapp/octonius-prod:users-server
    ports:
      - 7000:7000
    volumes:
      - /usr/app/node_modules
      - production_users_uploads_data:/usr/app/uploads
    environment:
      - NODE_ENV=production
      - PORT=7000
      - HOST=0.0.0.0
      - JWT_KEY=asfsaf12safas23fsafa12sf
      - dbURL=mongodb://mongodb:27017/octonius
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SENDGRID_KEY=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
      - SK_STRIPE=sk_live_WupyMoQf93S59gwTqmYpmWel
      - stripe_plan=plan_EK1rDLfKr9NRkU
      - WEBHOOK_PS_SECRET=whsec_pmcLdxoYxBAdZswT2ZzWYep2WmnBW8Sn
      - HEADER_EXTERNAL_KEY=HEADERIDSHAREDFOROCTONIUS
      - PROTOCOL=https
      - DOMAIN=app.octonius.com
    depends_on:
      - mongodb
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    networks:
      - production
      
  posts-server:
    image: octoniusapp/octonius-prod:posts-server
    ports:
      - 8000:8000
    volumes:
      - /usr/app/node_modules
      - production_posts_uploads_data:/usr/app/uploads
    environment:
      - NODE_ENV=production
      - PORT=8000
      - HOST=0.0.0.0
      - JWT_KEY=asfsaf12safas23fsafa12sf
      - dbURL=mongodb://mongodb:27017/octonius
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SENDGRID_KEY=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
      - SK_STRIPE=sk_live_WupyMoQf93S59gwTqmYpmWel
      - stripe_plan=plan_EK1rDLfKr9NRkU
      - WEBHOOK_PS_SECRET=whsec_pmcLdxoYxBAdZswT2ZzWYep2WmnBW8Sn
      - HEADER_EXTERNAL_KEY=HEADERIDSHAREDFOROCTONIUS
      - PROTOCOL=https
      - DOMAIN=app.octonius.com
    depends_on:
      - mongodb
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    networks:
      - production
      
  notifications-server:
    image: octoniusapp/octonius-prod:notifications-server
    ports:
      - 9000:9000
    volumes:
      - /usr/app/node_modules
    environment:
      - NODE_ENV=production
      - PORT=9000
      - HOST=0.0.0.0
      - JWT_KEY=asfsaf12safas23fsafa12sf
      - dbURL=mongodb://mongodb:27017/octonius
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SENDGRID_KEY=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
      - SK_STRIPE=sk_live_WupyMoQf93S59gwTqmYpmWel
      - stripe_plan=plan_EK1rDLfKr9NRkU
      - WEBHOOK_PS_SECRET=whsec_pmcLdxoYxBAdZswT2ZzWYep2WmnBW8Sn
      - HEADER_EXTERNAL_KEY=HEADERIDSHAREDFOROCTONIUS
      - PROTOCOL=https
      - DOMAIN=app.octonius.com
    depends_on:
      - mongodb
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    networks:
      - production
      
  utilities-server:
    image: octoniusapp/octonius-prod:utilities-server
    ports:
      - 10000:10000
    volumes:
      - /usr/app/node_modules
      - production_utilities_uploads_data:/usr/app/uploads
    environment:
      - NODE_ENV=production
      - PORT=10000
      - HOST=0.0.0.0
      - JWT_KEY=asfsaf12safas23fsafa12sf
      - dbURL=mongodb://mongodb:27017/octonius
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SENDGRID_KEY=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
      - SK_STRIPE=sk_live_WupyMoQf93S59gwTqmYpmWel
      - stripe_plan=plan_EK1rDLfKr9NRkU
      - WEBHOOK_PS_SECRET=whsec_pmcLdxoYxBAdZswT2ZzWYep2WmnBW8Sn
      - HEADER_EXTERNAL_KEY=HEADERIDSHAREDFOROCTONIUS
      - PROTOCOL=https
      - DOMAIN=app.octonius.com
    depends_on:
      - mongodb
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    networks:
      - production

  folio-server:
    image: octoniusapp/octonius-prod:folio-server
    ports:
      - 11000:11000
    volumes:
      - /usr/app/node_modules
    environment:
      - NODE_ENV=production
      - PORT=11000
      - HOST=0.0.0.0
      - JWT_KEY=asfsaf12safas23fsafa12sf
      - dbURL=mongodb://mongodb:27017/octonius
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SENDGRID_KEY=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
      - SK_STRIPE=sk_live_WupyMoQf93S59gwTqmYpmWel
      - stripe_plan=plan_EK1rDLfKr9NRkU
      - WEBHOOK_PS_SECRET=whsec_pmcLdxoYxBAdZswT2ZzWYep2WmnBW8Sn
      - HEADER_EXTERNAL_KEY=HEADERIDSHAREDFOROCTONIUS
      - PROTOCOL=https
      - DOMAIN=app.octonius.com
    depends_on:
      - mongodb
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    networks:
      - production

  search-server:
    image: octoniusapp/octonius-prod:search-server
    ports:
      - 12000:12000
    volumes:
      - /usr/app/node_modules
      - production_search_uploads_data:/usr/app/uploads
    environment:
      - NODE_ENV=production
      - PORT=12000
      - HOST=0.0.0.0
      - JWT_KEY=asfsaf12safas23fsafa12sf
      - dbURL=mongodb://mongodb:27017/octonius
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SENDGRID_KEY=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
      - SK_STRIPE=sk_live_WupyMoQf93S59gwTqmYpmWel
      - stripe_plan=plan_EK1rDLfKr9NRkU
      - WEBHOOK_PS_SECRET=whsec_pmcLdxoYxBAdZswT2ZzWYep2WmnBW8Sn
      - HEADER_EXTERNAL_KEY=HEADERIDSHAREDFOROCTONIUS
      - PROTOCOL=https
      - DOMAIN=app.octonius.com
    depends_on:
      - mongodb
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    networks:
      - production

  integrations-server:
    image: octoniusapp/octonius-prod:integrations-server
    ports:
      - 13000:13000
    volumes:
      - /usr/app/node_modules
    environment:
      - NODE_ENV=production
      - PORT=13000
      - HOST=0.0.0.0
      - JWT_KEY=asfsaf12safas23fsafa12sf
      - dbURL=mongodb://mongodb:27017/octonius
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SENDGRID_KEY=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
      - SK_STRIPE=sk_live_WupyMoQf93S59gwTqmYpmWel
      - stripe_plan=plan_EK1rDLfKr9NRkU
      - WEBHOOK_PS_SECRET=whsec_pmcLdxoYxBAdZswT2ZzWYep2WmnBW8Sn
      - HEADER_EXTERNAL_KEY=HEADERIDSHAREDFOROCTONIUS
      - PROTOCOL=https
      - DOMAIN=app.octonius.com
    depends_on:
      - mongodb
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    networks:
      - production
      
  client:
    image: octoniusapp/octonius-prod:client
    volumes:
      - /usr/app/node_modules
    depends_on:
      - mongodb
      - mailing-server
      - auths-server
      - groups-server
      - workspaces-server
      - users-server
      - posts-server
      - notifications-server
      - utilities-server
      - folio-server
      - search-server
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    networks:
      - production

  nginx:
    image: octoniusapp/octonius-prod:nginx
    ports:
      - 8080:80
    depends_on:
      - mongodb
      - mailing-server
      - auths-server
      - groups-server
      - workspaces-server
      - users-server
      - posts-server
      - notifications-server
      - utilities-server
      - folio-server
      - search-server
      - client
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    networks:
      - production

volumes:
  production_db_data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data/db
      o: bind

  production_groups_uploads_data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data/uploads/groups
      o: bind
  
  production_posts_uploads_data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data/uploads/posts
      o: bind

  production_users_uploads_data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data/uploads/users
      o: bind

  production_workspaces_uploads_data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data/uploads/workspaces
      o: bind

  production_utilities_uploads_data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data/uploads/utilities
      o: bind
  
  production_search_uploads_data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data/uploads/search
      o: bind 

networks:
  production: